spring:
  application:
    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/pedrocasseb/ecommerce-masteclass-microservices
#          default-label: main
#          search-paths: additional/config-management/app-configuration
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/config-db
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT prop_key, prop_value FROM tb_properties WHERE application=? AND profile=? AND label=?;"
          default-label: main
server:
  port: 8888

encrypt:
#  key: "0E329232EA6D0D73"
  key-store:
    location: config-server.jks
    password: ${KEY_PASSWORD}
    alias: config-server-key
